image: node:6.11.3

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm test
          - npm run build
  branches:
    develop:
      - step:
          name: Build and test
          caches:
            - node
          script:
            - npm install
            - npm test
            - npm run build
          artifacts:
            - build/**
      - step:
          name: Deploy
          deployment: staging
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
            - apt-get update && apt-get install -y python-dev
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - python get-pip.py
            - pip install awscli
            - aws s3 sync --delete $BITBUCKET_CLONE_DIR/build/ s3://$S3_BUCKET
